config/routes.rb
AmcmsFilemanager::Engine.routes.draw do
  get :filemanager, to: 'filemanager#index'
  namespace :filemanager do
    get :change_directory
    post :mkdir
    post :copy
    post :upload
    put :rename
    delete :destroy
  end
  resources :imagemanager
end

app/models/amcms_filemanager/application_record.rb
module AmcmsFilemanager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/amcms_filemanager/application_controller.rb
module AmcmsFilemanager
  class ApplicationController < ActionController::Base
    before_action :authenticate

    def authenticate
      return unless AmcmsFilemanager.config.try(:authentication).present?

      send("authenticate_#{AmcmsFilemanager.config.authentication[:model]}!")
    end
  end
end

app/controllers/amcms_filemanager/filemanager_controller.rb
# frozen_string_literal: true

module AmcmsFilemanager
  class FilemanagerController < ApplicationController
    before_action :item_exists?, only: %i[mkdir rename]

    def index
      @config = {
        routes: {
          cd_path: filemanager_change_directory_path,
          mkdir_path: filemanager_mkdir_path,
          rm_path: filemanager_destroy_path,
          rename_path: filemanager_rename_path,
          copy_path: filemanager_copy_path,
          image_info_path: imagemanager_path(':id'),
        },
        type: params.fetch(:type, 'all')
      }
    end

    def change_directory
      @files = AmcmsFilemanager::Filemanager.list(params[:cd], params[:type])

      render json: {
        files: @files,
        pwd: pwd,
        pwd_name: pwd.split('/').last,
        root_directory: AmcmsFilemanager.config.root_path,
        parent_directory: AmcmsFilemanager::Filemanager.parent_dir(params[:cd])
      }
    end

    def copy
      if AmcmsFilemanager::Filemanager.copy(params[:item_name])
        render json: { success: true }, status: 200
      else
        render json: { success: false }, status: 400
      end
    end

    def mkdir
      if AmcmsFilemanager::Filemanager.mkdir(params[:pwd], params[:item_name])
        render json: { success: true }, status: 200
      else
        render json: { success: false }, status: 400
      end
    end

    def rename
      if AmcmsFilemanager::Filemanager.rename(params[:pwd], params[:original_filename], params[:item_name])
        render json: { success: true }, status: 200
      else
        render json: { success: false }, status: 400
      end
    end

    def destroy
      if AmcmsFilemanager::Filemanager.delete(params[:file])
        render json: { success: true }, status: 200
      else
        render json: { success: false }, status: 400
      end
    end

    def upload
      if AmcmsFilemanager::Filemanager::upload(params[:dir], params[:file], params[:type])
        render json: { success: true }, status: 200
      else
        render json: { success: false }, status: 400
      end
    rescue CarrierWave::IntegrityError => e
      render json: { error: e.message }, status: 400
    end

    private

    def item_exists?
      return true unless AmcmsFilemanager::Filemanager.exists?(params[:pwd], params[:item_name])

      message = {
        title: 'Error',
        body: 'Item already exists. Please try a different name',
        status: 'danger'
      }
      render json: { success: false, message: message }, status: 400
      false
    end

    def pwd
      @pwd ||= params[:cd].blank? ? AmcmsFilemanager.config.root_path : params[:cd].gsub(%r{^/}, '')
    end
  end
end

app/controllers/amcms_filemanager/imagemanager_controller.rb
# frozen_string_literal: true

module AmcmsFilemanager
  class ImagemanagerController < ApplicationController
    def update
      uploader = AmcmsFilemanager::FilemanagerUploader.new
      uploader.retrieve_from_store!(source_file)
      uploader.resize_to_fit(params[:width], params[:height])
      render json: { success: true }
    rescue StandardError => e
      render json: { success: false, message: e.message }, status: 400
    end 

    def show
      if AmcmsFilemanager::Filemanager.image?(source_file)
        uploader = AmcmsFilemanager::FilemanagerUploader.new
        uploader.retrieve_from_store!(source_file)
        render json: { success: true, filepath: filepath, width: uploader.width, height: uploader.height, size: uploader.size }
      else
        render json: { success: false, error: 'File is not an image' }, status: 400
      end
    end

    private

    def source_file
      @source_file ||= params[:copy] ? AmcmsFilemanager::Filemanager.copy(filepath) : Rails.root.join('public', filepath)
    end

    def filepath
      "#{params[:id]}.#{params[:format]}".gsub(%r{^/}, '')
    end
  end
end

app/helpers/amcms_filemanager/application_helper.rb
module AmcmsFilemanager
  module ApplicationHelper
  end
end

app/helpers/amcms_filemanager/filemanager_helper.rb
module AmcmsFilemanager
  module FilemanagerHelper
  end
end

app/views/amcms_filemanager/filemanager/index.html.erb
<div id="amcms-filemanager-container" data-routes="<%= @config[:routes].to_json %>" data-type="<%= @config[:type] %>">
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light mb-3 fm">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-plus-lg"></i>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li id="fm-mkdir-item">
              <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#createFolderModal" href="#">
                <i class="bi bi-folder-plus"></i>
                Create Folder
              </a>
            </li>
            <li id="fm-upload-item">
              <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#uploadModal" href="#">
                <i class="bi bi-cloud-arrow-up"></i>
                Upload
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item"><a class="nav-link" id="pwd-display"></a></li>
      </ul>
      <ul class="navbar-nav ms-auto" id="file-list-type">
        <% if @config[:type] == 'image' %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#" id="thumbnail-view-btn" onclick="switchViewHandler(this, 'thumbnail')">
            <i class="bi bi-grid-fill"></i>
            Thumbnails
          </a>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link<%= @config[:type] == 'file' ? ' active' : '' %>" aria-current="page" href="#" id="list-view-btn" onclick="switchViewHandler(this, 'list')">
            <i class="bi bi-list-ul"></i>
            List
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="fm-file-panel">
    <div class="row" style="padding: 0 15px;">
      <div id="fm-directory-structure" class="col-md-3 ">
        <ul id="fm-directories-list" class="list-group position-static">

        </ul>
      </div>
      <div id="fm-directory-listing" class="col-md-9" style="overflow: auto">
        <div class="row" id="fm-file-list">

        </div>
      </div>
    </div>
  </div>
  <!-- Create Folder Modal -->
  <div class="modal fade" id="createFolderModal" tabindex="-1" aria-labelledby="createFolderModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createFolderModalLabel">Create Folder</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="fm-new-folder-form">
            <input type="text" name="item_name" id="new-folder-name" class="form-control" placeholder="Folder Name">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" onclick="createDirectory()">Create</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Rename Item Modal -->
  <div class="modal fade" id="renameItemModal" tabindex="-1" aria-labelledby="renameItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="renameItemModalLabel">Rename Item</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="fm-rename-item-form">
            <input type="text" name="item_name" id="new-filename" class="form-control" placeholder="Rename">
            <input type="hidden" name="original_filename" id="original-filename">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" onclick="renameFilename()">Rename</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Warning Modal -->
  <div class="modal" tabindex="-1" id="fmModal" aria-labelledby="fmModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header alert" id="fm-modal-header">
          <h5 class="modal-title fm-modal-title">Title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body fm-modal-body">
        </div>
        <div class="modal-footer fm-modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <div class="fm-modal-footer-buttons"></div>
        </div>
      </div>
    </div>
  </div>
  <!-- Upload Modal -->
  <div class="modal fade" tabindex="-1" id="uploadModal" aria-labelledby="uploadModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header alert" id="fm-upload-header">
          <h5 class="modal-title upload-modal-title">Upload Files</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body upload-modal-body">
          <form action="<%= filemanager_upload_path(type: @config[:type]) %>" class="dropzone" id="fm-uploader">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <input type="hidden" name="dir" id="upload_to_dir">
          </form>
        </div>
        <div class="modal-footer upload-modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Resize Image Modal -->
  <div class="modal fade" id="resizeImageModal" tabindex="-1" aria-labelledby="resizeImageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="imageResizeModalLabel">Resize Image</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-8" id="image-preview-panel">
              <img src="" alt="" id="original_image">
            </div>
            <div class="col-4">
              <form id="fm-resize-image-form">
                <h6>Image Details</h6>
                <div id="image-info-container">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-secondary" onclick="resizeImageHandler(true)">Resize and Save Copy</button>
          <button type="button" class="btn btn-primary" onclick="resizeImageHandler(false)">Resize and Save</button>
        </div>
      </div>
    </div>
  </div>

</div>